"""Add user_id to LoveHistory

Revision ID: dbbd401ddf8e
Revises: 
Create Date: 2025-05-27 08:52:36.265518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbbd401ddf8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('love_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('name1', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('name2', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('msg', sa.Text(), nullable=False))
        batch_op.create_foreign_key(
            'fk_love_history_user_id_user',
            'user',
            ['user_id'],
            ['id']
        )
        batch_op.drop_column('target_name')
        batch_op.drop_column('result')
        batch_op.drop_column('user_email')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('love_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('result', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('target_name', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint('fk_love_history_user_id_user', type_='foreignkey')  # ✅ 이름 명시
        batch_op.drop_column('msg')
        batch_op.drop_column('score')
        batch_op.drop_column('name2')
        batch_op.drop_column('name1')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
